/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Nov 13 23:01:00 2017. */

#include "SorecoProtocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t WifiConfigMessage_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, WifiConfigMessage, ssid, ssid, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, WifiConfigMessage, password, ssid, 0),
    PB_LAST_FIELD
};

const pb_field_t Protocol_fields[3] = {
    PB_ONEOF_FIELD(payload,   1, ENUM    , ONEOF, STATIC  , FIRST, Protocol, Response, Response, 0),
    PB_ONEOF_FIELD(payload,   5, MESSAGE , ONEOF, STATIC  , UNION, Protocol, WifiConfig, WifiConfig, &WifiConfigMessage_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Protocol, payload.WifiConfig) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_WifiConfigMessage_Protocol)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Protocol, payload.WifiConfig) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_WifiConfigMessage_Protocol)
#endif


/* @@protoc_insertion_point(eof) */
