/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sat Nov 18 16:54:54 2017. */

#ifndef PB_SORECOPROTOCOL_PB_H_INCLUDED
#define PB_SORECOPROTOCOL_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ResponseType {
    ResponseType_OK = 200,
    ResponseType_ERROR = 404
} ResponseType;
#define _ResponseType_MIN ResponseType_OK
#define _ResponseType_MAX ResponseType_ERROR
#define _ResponseType_ARRAYSIZE ((ResponseType)(ResponseType_ERROR+1))

typedef enum _ScanWifiMessage_EncTypes {
    ScanWifiMessage_EncTypes_ENC_TYPE_WEP = 1,
    ScanWifiMessage_EncTypes_ENC_TYPE_TKIP = 2,
    ScanWifiMessage_EncTypes_ENC_TYPE_CCMP = 3,
    ScanWifiMessage_EncTypes_ENC_TYPE_NONE = 7,
    ScanWifiMessage_EncTypes_ENC_TYPE_AUTO = 8
} ScanWifiMessage_EncTypes;
#define _ScanWifiMessage_EncTypes_MIN ScanWifiMessage_EncTypes_ENC_TYPE_WEP
#define _ScanWifiMessage_EncTypes_MAX ScanWifiMessage_EncTypes_ENC_TYPE_AUTO
#define _ScanWifiMessage_EncTypes_ARRAYSIZE ((ScanWifiMessage_EncTypes)(ScanWifiMessage_EncTypes_ENC_TYPE_AUTO+1))

/* Struct definitions */
typedef struct _ScanWifiMessage {
    pb_callback_t Wlans;
/* @@protoc_insertion_point(struct:ScanWifiMessage) */
} ScanWifiMessage;

typedef struct _ScanWifiMessage_Wlan {
    char ssid[32];
    bool has_EncType;
    ScanWifiMessage_EncTypes EncType;
    bool has_SignalStrength;
    int32_t SignalStrength;
/* @@protoc_insertion_point(struct:ScanWifiMessage_Wlan) */
} ScanWifiMessage_Wlan;

typedef struct _WifiConfigMessage {
    bool has_ssid;
    char ssid[32];
    bool has_password;
    char password[64];
/* @@protoc_insertion_point(struct:WifiConfigMessage) */
} WifiConfigMessage;

typedef struct _Protocol {
    pb_size_t which_payload;
    union {
        ResponseType Response;
        WifiConfigMessage WifiConfig;
        ScanWifiMessage ScanWifiMessage;
    } payload;
/* @@protoc_insertion_point(struct:Protocol) */
} Protocol;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Protocol_init_default                    {0, {(ResponseType)0}}
#define WifiConfigMessage_init_default           {false, "", false, ""}
#define ScanWifiMessage_init_default             {{{NULL}, NULL}}
#define ScanWifiMessage_Wlan_init_default        {"", false, (ScanWifiMessage_EncTypes)0, false, 0}
#define Protocol_init_zero                       {0, {(ResponseType)0}}
#define WifiConfigMessage_init_zero              {false, "", false, ""}
#define ScanWifiMessage_init_zero                {{{NULL}, NULL}}
#define ScanWifiMessage_Wlan_init_zero           {"", false, (ScanWifiMessage_EncTypes)0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ScanWifiMessage_Wlans_tag                1
#define ScanWifiMessage_Wlan_ssid_tag            2
#define ScanWifiMessage_Wlan_EncType_tag         3
#define ScanWifiMessage_Wlan_SignalStrength_tag  4
#define WifiConfigMessage_ssid_tag               1
#define WifiConfigMessage_password_tag           2
#define Protocol_Response_tag                    1
#define Protocol_WifiConfig_tag                  5
#define Protocol_ScanWifiMessage_tag             6

/* Struct field encoding specification for nanopb */
extern const pb_field_t Protocol_fields[4];
extern const pb_field_t WifiConfigMessage_fields[3];
extern const pb_field_t ScanWifiMessage_fields[2];
extern const pb_field_t ScanWifiMessage_Wlan_fields[4];

/* Maximum encoded size of messages (where known) */
/* Protocol_size depends on runtime parameters */
#define WifiConfigMessage_size                   100
/* ScanWifiMessage_size depends on runtime parameters */
#define ScanWifiMessage_Wlan_size                47

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SORECOPROTOCOL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
